### ISSUE TITLE
BitsInput in PHP

### ISSUE THREAD

**Issue by clemos** [HaxeFoundation/format#34]
I'm trying to use `format.swf` in PHP (on Ubuntu 64bit).
I've started by implementing `Compress/Uncompress` for PHP, which seems to work,
but now I'm hitting an issue with `format.tools.BitsInput`, which I believe is related to this haxe issue, as it only affects the PHP target:
https://github.com/HaxeFoundation/haxe/issues/3414
I've been trying to use `Int32` instead of `Int`, without success.
Can someone help me find a workaround ?
If it helps, I can probably come up with a simple test to reproduce the issue.

**Comment by ncannasse** [comment]
Could you try to produce some code that gives different results in PHP vs JS  ? First using format.tools.BitsInput, then without it (plain Haxe code). Then you're ready to fill a bug :) The issue you're referring too might not be the culprit, given it deals with differences between compile-time and runtime behavior due to haxe compiler optimization, while BitsInput only perform runtime checks.

**Comment by clemos** [comment]
Here are some tests, without `BitsInput` : 
https://gist.github.com/clemos/fc48d8076d936531a386
Fixing them at the compiler level would certainly help fix the issue with `BitsInput`.

**Comment by clemos** [comment]
It seems the fix I provided here fixes this issue:
https://github.com/HaxeFoundation/haxe/pull/4571
Thanks for your help
